"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Download, FileText, Mail, ChevronDown, ChevronUp } from "lucide-react"
import { Input } from "@/components/ui/input"

interface ExportManagerProps {
  analysisData: any
  brandName: string
}

export function ExportManager({ analysisData, brandName }: ExportManagerProps) {
  const [isExpanded, setIsExpanded] = useState(false)
  const [sections, setSections] = useState({
    summary: true,
    trends: true,
    regions: true,
    personas: true,
    competitors: true,
    context: true,
    links: true,
    actions: true,
  })
  const [emailSchedule, setEmailSchedule] = useState<"none" | "weekly" | "monthly">("none")
  const [email, setEmail] = useState("")

  const generatePDFReport = () => {
    const reportHTML = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${brandName} - Brand Visibility Report</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; max-width: 1000px; margin: 0 auto; }
          h1 { color: #1e40af; border-bottom: 3px solid #1e40af; padding-bottom: 10px; }
          h2 { color: #3b82f6; margin-top: 30px; }
          .metric { background: #eff6ff; padding: 15px; margin: 10px 0; border-radius: 8px; }
          .score { font-size: 48px; font-weight: bold; color: #1e40af; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
          th { background: #f3f4f6; font-weight: 600; }
          .positive { color: #16a34a; }
          .negative { color: #dc2626; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <h1>Brand Visibility Analysis Report</h1>
        <p><strong>Brand:</strong> ${brandName}</p>
        <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
        
        ${
          sections.summary
            ? `
        <h2>Executive Summary</h2>
        <div class="metric">
          <div>Overall Visibility Score</div>
          <div class="score">${Math.round(analysisData.globalScore || 0)}/100</div>
        </div>
        `
            : ""
        }
        
        ${
          sections.competitors
            ? `
        <h2>Competitive Position</h2>
        <table>
          <tr><th>Brand</th><th>Mentions</th><th>Avg Position</th><th>Sentiment</th></tr>
          ${(analysisData.competitorMentions || [])
            .slice(0, 5)
            .map(
              (c: any) => `
            <tr>
              <td>${c.brand}</td>
              <td>${c.count}</td>
              <td>${c.avgPosition?.toFixed(1)}</td>
              <td>${c.sentiment}</td>
            </tr>
          `,
            )
            .join("")}
        </table>
        `
            : ""
        }
        
        ${
          sections.regions
            ? `
        <h2>Regional Performance</h2>
        <table>
          <tr><th>Region</th><th>Score</th></tr>
          ${(analysisData.regionPerformance || [])
            .map(
              (r: any) => `
            <tr><td>${r.region.toUpperCase()}</td><td>${Math.round(r.score)}</td></tr>
          `,
            )
            .join("")}
        </table>
        `
            : ""
        }
        
        <p style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px;">
          Generated by BrandVision AI - Brand Visibility Analysis Tool
        </p>
      </body>
      </html>
    `

    const blob = new Blob([reportHTML], { type: "text/html" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = `${brandName.replace(/\s+/g, "-")}-report-${Date.now()}.html`
    link.click()
    URL.revokeObjectURL(url)
  }

  const exportToJSON = () => {
    const exportData = {
      brand: brandName,
      generatedAt: new Date().toISOString(),
      sections: sections,
      data: analysisData,
    }

    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: "application/json" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = `${brandName.replace(/\s+/g, "-")}-data-${Date.now()}.json`
    link.click()
    URL.revokeObjectURL(url)
  }

  const scheduleReport = () => {
    if (!email || emailSchedule === "none") {
      alert("Please enter an email and select a schedule")
      return
    }

    // This would integrate with your backend to schedule emails
    alert(`Report scheduled ${emailSchedule} to ${email}`)
  }

  return (
    <div className="space-y-2">
      <Button variant="outline" onClick={() => setIsExpanded(!isExpanded)} className="w-full justify-between">
        <span className="flex items-center gap-2">
          <Download className="h-4 w-4" />
          Export & Scheduling
        </span>
        {isExpanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
      </Button>

      {isExpanded && (
        <Card>
          <CardHeader>
            <CardTitle>Export & Scheduling</CardTitle>
            <CardDescription>Export reports and schedule automated updates</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Section Selection */}
            <div>
              <h3 className="font-semibold mb-3">Include in Report</h3>
              <div className="grid grid-cols-2 gap-3">
                {Object.entries(sections).map(([key, value]) => (
                  <div key={key} className="flex items-center gap-2">
                    <Checkbox
                      id={key}
                      checked={value}
                      onCheckedChange={(checked) => setSections((prev) => ({ ...prev, [key]: !!checked }))}
                    />
                    <Label htmlFor={key} className="capitalize cursor-pointer">
                      {key}
                    </Label>
                  </div>
                ))}
              </div>
            </div>

            {/* Export Buttons */}
            <div className="flex gap-3">
              <Button onClick={generatePDFReport} className="flex-1">
                <FileText className="mr-2 h-4 w-4" />
                Export PDF
              </Button>
              <Button onClick={exportToJSON} variant="outline" className="flex-1 bg-transparent">
                <Download className="mr-2 h-4 w-4" />
                Export JSON
              </Button>
            </div>

            {/* Email Scheduling */}
            <div className="space-y-3 pt-4 border-t">
              <h3 className="font-semibold">Schedule Reports</h3>
              <div className="space-y-2">
                <Input
                  type="email"
                  placeholder="Email address"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
                <div className="flex gap-2">
                  <Button
                    variant={emailSchedule === "weekly" ? "default" : "outline"}
                    onClick={() => setEmailSchedule("weekly")}
                    className="flex-1"
                  >
                    Weekly
                  </Button>
                  <Button
                    variant={emailSchedule === "monthly" ? "default" : "outline"}
                    onClick={() => setEmailSchedule("monthly")}
                    className="flex-1"
                  >
                    Monthly
                  </Button>
                </div>
                <Button onClick={scheduleReport} className="w-full" disabled={!email || emailSchedule === "none"}>
                  <Mail className="mr-2 h-4 w-4" />
                  Schedule Email Reports
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
